### ISSUE TITLE
Review Contributing.md

### ISSUE THREAD

**Issue by mikecargal** [emergentworks/curriculum#57]
Just noticed the Contributing.md file.

It appears as though it was inherited from some "Moya" project, and still contains references to that project.

If we want to follow those contribution guidelines, we need to reword this document to refer to the EmergentWorks curriculum project.

It also mentions that they open the project to push requests.   I don't know if this repo accepts unsolicited pushes (that would be unusual).  If it doesn't, then this document needs to be reworded (significantly, since it's mostly about the implications of that decision).   If this repo does accept pushes, that should be a conscious decision, and we should reword this a bit so that it's clear that it refers to the EmergentWorks curriculum repo.

I don't mind taking a shot at cleaning it up, but would need to know what our intentions are.

**Comment by ashley** [comment]
For now, let's remove the file since the committee are the owners of this repository. In the long run, we can think of how we can open this curriculum to contributions outside of the committee.

**Comment by mikecargal** [comment]
OK... it's gone
